### ISSUE TITLE
it not working in android 

### ISSUE THREAD

**Issue by singharyan015** [bcko/flutter_qrcode_reader#46]
`E/flutter ( 5660): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method readQRCode on channel qrcode_reader)
E/flutter ( 5660): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
E/flutter ( 5660): <asynchronous suspension>
E/flutter ( 5660): #1      QRCodeReader.scan (package:qrcode_reader/qrcode_reader.dart:67:27)
E/flutter ( 5660): <asynchronous suspension>
E/flutter ( 5660): #2      _qrCodeState.build.<anonymous closure>.<anonymous closure> (package:qrcode/main.dart:57:18)
E/flutter ( 5660): #3      State.setState (package:flutter/src/widgets/framework.dart:1117:30)
E/flutter ( 5660): #4      _qrCodeState.build.<anonymous closure> (package:qrcode/main.dart:50:11)
E/flutter ( 5660): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
E/flutter ( 5660): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
E/flutter ( 5660): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
E/flutter ( 5660): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
E/flutter ( 5660): #9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:211:7)
E/flutter ( 5660): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 5660): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:225:20)
E/flutter ( 5660): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
E/flutter ( 5660): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 5660): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 5660): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 5660): #16     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 5660): #17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 5660): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 5660): #19     _invoke1 (dart:ui/hooks.dart:233:10)
E/flutter ( 5660): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
E/flutter ( 5660): 
`

**Comment by EndersonPro** [comment]
I have the same problem.

**Comment by ManildraMattL** [comment]
If you fully exit the app (use app switcher, not back button) do you get the same problem?

**Comment by peterlauri** [comment]
I had the same problem when trying to use the library. Fully exit the app did not work either. I have drilled down to that there are some fundamental problems with the package it self. See https://github.com/bcko/flutter_qrcode_reader/issues/61.

**Comment by Wmeng22** [comment]
I have the same problem.
