### ISSUE TITLE
I cannot use this plugin It has this error

### ISSUE THREAD

**Issue by hieuhd1** [bcko/flutter_qrcode_reader#62]
E/flutter (12364): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method readQRCode on channel qrcode_reader)
E/flutter (12364): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (12364): <asynchronous suspension>                            
E/flutter (12364): #1      QRCodeReader.scan (package:qrcode_reader/qrcode_reader.dart:74:27)

I tried with all the same issues but still the same error.

qrcode_reader:
    git: https://github.com/bcko/flutter_qrcode_reader.git

**Comment by nigga1604** [comment]
Yeah same error for me too i am not getting any idea hoe to solve it if anyone can help????pls help us

**Comment by elvincali** [comment]
> Yeah same error for me too i am not getting any idea hoe to solve it if anyone can help????pls help us

https://github.com/bcko/flutter_qrcode_reader/pull/57#issuecomment-575262152

**Comment by johanhenselmans** [comment]
Did you try 
qrcode_reader:
    git: https://github.com/bcko/flutter_qrcode_reader.git

in your pubspec.yaml?

Unfortunately I can not publish to pub.dev.

**Comment by LeanGardella** [comment]
Same problem here! 
I decided to change to qrscan 0.2.17 which works fine!

**Comment by oscarcolima** [comment]
> Same problem here!
> I decided to change to qrscan 0.2.17 which works fine!

qr scan 0.2.17 does not work to ios be careful

**Comment by NaagAlgates** [comment]
As suggested by @johanhenselmans , use this in your pubsec.yaml

qrcode_reader:
git: https://github.com/bcko/flutter_qrcode_reader.git
